services:
  wordpress:
    image: wordpress:latest
    restart: always
    volumes:
      - ./public:/var/www/html

  php:
    build: ./docker/php
    restart: always
    volumes:
      - ./public:/var/www/html
    working_dir: /var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: $DB_NAME
      WORDPRESS_DB_USER: $DB_USER
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD

  node:
    image: node:latest
    restart: always
    volumes:
      - ./public:/var/www/html
    working_dir: /var/www/html/wp-content
    command: tail -f /dev/null
    environment:
      NODE_ENV: development

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    ports:
      - "$PHP_MY_ADMIN_PORT:80"
    depends_on:
      - db

  site:
    image: nginx:latest
    restart: always
    ports:
      - "$SERVER_PORT:80"
    volumes:
      - ./public:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - wordpress

volumes:
  db_data: